// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskBoard.Data;

#nullable disable

namespace Board.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250630201257_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskBoard.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = "John Doe",
                            CreatedAt = new DateTime(2025, 6, 28, 20, 12, 57, 239, DateTimeKind.Utc).AddTicks(6650),
                            Description = "Initialize the TaskBoard project",
                            Status = "Completed",
                            Title = "Setup Project"
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = "Jane Smith",
                            CreatedAt = new DateTime(2025, 6, 29, 20, 12, 57, 239, DateTimeKind.Utc).AddTicks(6660),
                            Description = "Define TaskItem model",
                            Status = "In Progress",
                            Title = "Create Models"
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = "Bob Johnson",
                            CreatedAt = new DateTime(2025, 6, 30, 20, 12, 57, 239, DateTimeKind.Utc).AddTicks(6662),
                            Description = "Create the user interface",
                            Status = "To Do",
                            Title = "Build UI"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
